server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://ep-damp-violet-a1fw4dlo.ap-southeast-1.aws.neon.tech:5432/comsense?sslmode=require
    username: comsense_owner
    password: 3ToqjWZFsYO2
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  application:
    name: ms-admin

  devtools:
    restart:
      enabled: true


#logging:
#  level:
#    org.springframework.security: DEBUG


jwt:
  secret: YmU2ZDc5MTE5ZDAxZGFmMGQyYzgzZmZlMmZkMWFiMjVmYzBjMzIzZDEzZGM5N2IxZGZlNjU0ODQ2MDQwNzI5ZjFhOGEyNGY4N2M5OTlhMjMxNDVlOTJkODBhMGVkNGM5NWE4NjAxZWI1Y2ZiNWVlN2JhNThkMGQxYjhmMzczYTA=
